-- Real parts for Solar Builder.
-- Generated by catalog/emit_sql.py from web/catalog.json. Do not hand-edit.
--
-- The app reads these eight tables through its catalog server function,
-- so nothing in src/ has to change. Safe to re-run.

BEGIN;

-- Visitor drafts reference the demo part ids. They are fictional, and the
-- rows below replace them, so the drafts go first rather than block the
-- delete with a foreign key error. Checklist rows follow via ON DELETE
-- CASCADE from saved_builds.
DELETE FROM public.checklist_items;
DELETE FROM public.saved_builds;

-- CEC publishes no warranty figure for solar modules. The column is
-- NOT NULL and our source has no value, so relax it rather than invent
-- one. The app does not read this field.
ALTER TABLE public.panels ALTER COLUMN warranty_years DROP NOT NULL;

-- The household the demo starts from
INSERT INTO public.households (household_id,name,location,timezone,monthly_consumption_kwh,budget_php,system_type,critical_load_kw,target_backup_hours,tariff_php_per_kwh,peak_sun_hours,performance_ratio,is_synthetic) VALUES
('HH001','Demo Household','Laguna, Philippines','Asia/Manila',450,250000,'hybrid',0.5,8,12,4.5,0.8,true)
ON CONFLICT (household_id) DO UPDATE SET name = excluded.name, location = excluded.location, timezone = excluded.timezone, monthly_consumption_kwh = excluded.monthly_consumption_kwh, budget_php = excluded.budget_php, system_type = excluded.system_type, critical_load_kw = excluded.critical_load_kw, target_backup_hours = excluded.target_backup_hours, tariff_php_per_kwh = excluded.tariff_php_per_kwh, peak_sun_hours = excluded.peak_sun_hours, performance_ratio = excluded.performance_ratio, is_synthetic = excluded.is_synthetic;


-- 61 panels
INSERT INTO public.panels (panel_id,name,rated_power_w,vmp_v,imp_a,voc_v,isc_a,warranty_years) VALUES
('cec-rec-group-rec740aa-pro-xl','REC Group REC740AA Pro XL',740.0,46.3,15.97,53.8,16.75,NULL),
('cec-trina-solar-tsm-740neg21c20','Trina Solar TSM-740NEG21C20',740.0,42.1,17.58,50.3,18.66,NULL),
('cec-trina-solar-tsm-735neg21c20','Trina Solar TSM-735NEG21C20',735.0,41.9,17.55,50.1,18.62,NULL),
('cec-rec-group-rec730aa-pro-xl','REC Group REC730AA Pro XL',730.0,46.3,15.79,53.7,16.57,NULL),
('cec-risen-energy-co-ltd-rsm132-8-730bhdg','Risen Energy Co Ltd RSM132-8-730BHDG',730.0,42.2,17.32,50.33,18.38,NULL),
('cec-suzhou-talesun-solar-technologies-co-ltd','Suzhou Talesun Solar Technologies Co Ltd TM8G66M-730',730.0,41.7,17.51,49.8,18.57,NULL),
('cec-trina-solar-tsm-730neg21c20','Trina Solar TSM-730NEG21C20',730.0,41.7,17.51,49.9,18.58,NULL),
('cec-risen-energy-co-ltd-rsm132-8-725bhdg','Risen Energy Co Ltd RSM132-8-725BHDG',725.0,42.14,17.23,50.26,18.29,NULL),
('cec-suzhou-talesun-solar-technologies-co-ltd','Suzhou Talesun Solar Technologies Co Ltd TM8G66M-725',725.0,41.5,17.47,49.6,18.53,NULL),
('cec-trina-solar-coltd-tsm-725neg21c20','Trina Solar CoLtd TSM-725NEG21C20',725.0,41.5,17.47,49.6,18.54,NULL),
('cec-rec-group-rec720aa-pro-xl','REC Group REC720AA Pro XL',720.0,46.2,15.6,53.6,16.39,NULL),
('cec-risen-energy-co-ltd-rsm132-8-720bhdg','Risen Energy Co Ltd RSM132-8-720BHDG',720.0,42.08,17.13,50.18,18.19,NULL),
('cec-suzhou-talesun-solar-technologies-co-ltd','Suzhou Talesun Solar Technologies Co Ltd TM8G66M-720',720.0,41.3,17.44,49.4,18.49,NULL),
('cec-trina-solar-coltd-tsm-720neg21c20','Trina Solar CoLtd TSM-720NEG21C20',720.0,41.3,17.44,49.4,18.49,NULL),
('cec-risen-energy-co-ltd-rsm132-8-715bhdg','Risen Energy Co Ltd RSM132-8-715BHDG',715.0,42.01,17.03,50.09,18.08,NULL),
('cec-suzhou-talesun-solar-technologies-co-ltd','Suzhou Talesun Solar Technologies Co Ltd TM8G66M-715',715.0,41.1,17.4,49.2,18.44,NULL),
('cec-trina-solar-coltd-tsm-715neg21c20','Trina Solar CoLtd TSM-715NEG21C20',715.0,41.1,17.4,49.2,18.44,NULL),
('cec-risen-energy-co-ltd-rsm132-8-710bhdg','Risen Energy Co Ltd RSM132-8-710BHDG',710.0,41.93,16.95,50.01,18.0,NULL),
('cec-suzhou-talesun-solar-technologies-co-ltd','Suzhou Talesun Solar Technologies Co Ltd TM8G66M-710',710.0,40.9,17.36,49.0,18.4,NULL),
('cec-trina-solar-coltd-tsm-710neg21c20','Trina Solar CoLtd TSM-710NEG21C20',710.0,40.9,17.36,49.0,18.4,NULL),
('cec-risen-energy-co-ltd-rsm132-8-705bhdg','Risen Energy Co Ltd RSM132-8-705BHDG',705.0,41.86,16.86,49.92,17.91,NULL),
('cec-suzhou-talesun-solar-technologies-co-ltd','Suzhou Talesun Solar Technologies Co Ltd TM8G66M-705',705.0,40.7,17.33,48.8,18.36,NULL),
('cec-trina-solar-coltd-tsm-705neg21c20','Trina Solar CoLtd TSM-705NEG21C20',705.0,40.7,17.33,48.8,18.36,NULL),
('cec-risen-energy-co-ltd-rsm132-8-700bhdg','Risen Energy Co Ltd RSM132-8-700BHDG',700.0,41.78,16.77,49.83,17.82,NULL),
('cec-trina-solar-coltd-tsm-700neg21c20','Trina Solar CoLtd TSM-700NEG21C20',700.0,40.5,17.29,48.6,18.32,NULL),
('cec-risen-energy-co-ltd-rsm132-8-695bhdg','Risen Energy Co Ltd RSM132-8-695BHDG',695.0,41.71,16.68,49.74,17.74,NULL),
('cec-trina-solar-coltd-tsm-695neg21c20','Trina Solar CoLtd TSM-695NEG21C20',695.0,40.3,17.25,48.3,18.28,NULL),
('cec-risen-energy-co-ltd-rsm132-8-690bhdg','Risen Energy Co Ltd RSM132-8-690BHDG',690.0,41.63,16.6,49.65,17.66,NULL),
('cec-trina-solar-coltd-tsm-690neg21c20','Trina Solar CoLtd TSM-690NEG21C20',690.0,40.1,17.23,47.9,18.25,NULL),
('cec-risen-energy-co-ltd-rsm132-8-685bhdg','Risen Energy Co Ltd RSM132-8-685BHDG',685.0,41.56,16.5,49.56,17.56,NULL),
('cec-trina-solar-coltd-tsm-685neg21c20','Trina Solar CoLtd TSM-685NEG21C20',685.0,39.8,17.19,47.7,18.21,NULL),
('cec-rec-group-rec680aa-pro-l','REC Group REC680AA Pro L',680.0,42.6,16.01,49.3,16.76,NULL),
('cec-risen-energy-co-ltd-rsm132-8-680bhdg','Risen Energy Co Ltd RSM132-8-680BHDG',680.0,41.48,16.41,49.47,17.48,NULL),
('cec-trina-solar-coltd-tsm-680neg21c20','Trina Solar CoLtd TSM-680NEG21C20',680.0,39.6,17.16,47.4,18.18,NULL),
('cec-risen-energy-co-ltd-rsm132-8-675bhdg','Risen Energy Co Ltd RSM132-8-675BHDG',675.0,41.41,16.32,49.38,17.4,NULL),
('cec-trina-solar-coltd-tsm-675neg21c20','Trina Solar CoLtd TSM-675NEG21C20',675.0,39.4,17.12,47.2,18.14,NULL),
('cec-rec-group-rec670aa-pro-l','REC Group REC670AA Pro L',670.0,42.5,15.79,49.2,16.55,NULL),
('cec-risen-energy-co-ltd-rsm132-8-670bhdg','Risen Energy Co Ltd RSM132-8-670BHDG',670.0,41.33,16.23,49.29,17.31,NULL),
('cec-risen-energy-co-ltd-rsm132-8-670bmdg','Risen Energy Co Ltd RSM132-8-670BMDG',670.0,38.59,17.37,46.29,18.38,NULL),
('cec-risen-energy-co-ltd-rsm132-8-670m','Risen Energy Co Ltd RSM132-8-670M',670.0,38.48,17.42,46.15,18.43,NULL),
('cec-trina-solar-tsm-670de21','Trina Solar TSM-670DE21',670.0,38.2,17.55,46.1,18.62,NULL),
('cec-trina-solar-tsm-670deg21c20','Trina Solar TSM-670DEG21C20',670.0,38.5,17.43,46.3,18.55,NULL),
('cec-trina-solar-coltd-tsm-670neg21c20','Trina Solar CoLtd TSM-670NEG21C20',670.0,39.2,17.09,47.0,18.1,NULL),
('cec-risen-energy-co-ltd-rsm132-8-665bhdg','Risen Energy Co Ltd RSM132-8-665BHDG',665.0,41.25,16.14,49.2,17.22,NULL),
('cec-risen-energy-co-ltd-rsm132-8-665bmdg','Risen Energy Co Ltd RSM132-8-665BMDG',665.0,38.41,17.32,46.09,18.33,NULL),
('cec-risen-energy-co-ltd-rsm132-8-665m','Risen Energy Co Ltd RSM132-8-665M',665.0,38.3,17.37,45.95,18.38,NULL),
('cec-trina-solar-tsm-665de21','Trina Solar TSM-665DE21',665.0,38.0,17.51,45.9,18.57,NULL),
('cec-trina-solar-tsm-665deg21c20','Trina Solar TSM-665DEG21C20',665.0,38.3,17.39,46.1,18.5,NULL),
('cec-trina-solar-coltd-tsm-665neg21c20','Trina Solar CoLtd TSM-665NEG21C20',665.0,39.0,17.06,46.8,18.07,NULL),
('cec-rec-group-rec660aa-pro-l','REC Group REC660AA Pro L',660.0,42.4,15.6,49.2,16.35,NULL),
('cec-risen-energy-co-ltd-rsm132-8-660bhdg','Risen Energy Co Ltd RSM132-8-660BHDG',660.0,41.18,16.05,49.11,17.14,NULL),
('cec-risen-energy-co-ltd-rsm132-8-660bmdg','Risen Energy Co Ltd RSM132-8-660BMDG',660.0,38.23,17.27,45.89,18.28,NULL),
('cec-risen-energy-co-ltd-rsm132-8-660m','Risen Energy Co Ltd RSM132-8-660M',660.0,38.12,17.32,45.75,18.33,NULL),
('cec-trina-solar-tsm-660de21','Trina Solar TSM-660DE21',660.0,37.8,17.47,45.7,18.53,NULL),
('cec-trina-solar-tsm-660deg21c20','Trina Solar TSM-660DEG21C20',660.0,38.1,17.35,45.9,18.45,NULL),
('cec-trina-solar-coltd-tsm-660neg21c20','Trina Solar CoLtd TSM-660NEG21C20',660.0,38.8,17.02,46.6,18.03,NULL),
('cec-risen-energy-co-ltd-rsm132-8-655bhdg','Risen Energy Co Ltd RSM132-8-655BHDG',655.0,41.1,15.96,49.02,17.06,NULL),
('cec-risen-energy-co-ltd-rsm132-8-655bmdg','Risen Energy Co Ltd RSM132-8-655BMDG',655.0,38.05,17.22,45.69,18.23,NULL),
('cec-risen-energy-co-ltd-rsm132-8-655m','Risen Energy Co Ltd RSM132-8-655M',655.0,37.94,17.27,45.55,18.28,NULL),
('cec-trina-solar-tsm-655de21','Trina Solar TSM-655DE21',655.0,37.6,17.43,45.5,18.48,NULL),
('cec-ja-solar-jam72d30-550-mb','JA Solar JAM72D30-550/MB',550.0,41.96,13.11,49.9,14.0,NULL)
ON CONFLICT (panel_id) DO UPDATE SET name = excluded.name, rated_power_w = excluded.rated_power_w, vmp_v = excluded.vmp_v, imp_a = excluded.imp_a, voc_v = excluded.voc_v, isc_a = excluded.isc_a, warranty_years = excluded.warranty_years;


-- Hybrid inverters, 230 V
INSERT INTO public.inverters (inverter_id,name,system_type,rated_ac_power_kw,max_pv_power_kw,mppt_min_v,mppt_max_v,max_dc_voltage_v,max_mppt_current_a,max_mppt_isc_a,mppt_count,battery_min_v,battery_max_v,max_battery_power_kw,bms_family,monitoring_support) VALUES
('deye-sun-3k-sg04lp1-eu','Deye SUN-3K-SG04LP1-EU','hybrid',3.0,6.0,150.0,425.0,500.0,18.0,27.0,1,40.0,60.0,3.0,'Deye LV BMS','none'),
('deye-sun-3-6k-sg04lp1-eu','Deye SUN-3.6K-SG04LP1-EU','hybrid',3.6,7.2,150.0,425.0,500.0,18.0,27.0,1,40.0,60.0,3.6,'Deye LV BMS','none'),
('deye-sun-5k-sg04lp1-eu','Deye SUN-5K-SG04LP1-EU','hybrid',5.0,10.0,150.0,425.0,500.0,18.0,27.0,2,40.0,60.0,5.0,'Deye LV BMS','none'),
('deye-sun-6k-sg04lp1-eu','Deye SUN-6K-SG04LP1-EU','hybrid',6.0,12.0,150.0,425.0,500.0,18.0,27.0,2,40.0,60.0,6.0,'Deye LV BMS','none')
ON CONFLICT (inverter_id) DO UPDATE SET name = excluded.name, system_type = excluded.system_type, rated_ac_power_kw = excluded.rated_ac_power_kw, max_pv_power_kw = excluded.max_pv_power_kw, mppt_min_v = excluded.mppt_min_v, mppt_max_v = excluded.mppt_max_v, max_dc_voltage_v = excluded.max_dc_voltage_v, max_mppt_current_a = excluded.max_mppt_current_a, max_mppt_isc_a = excluded.max_mppt_isc_a, mppt_count = excluded.mppt_count, battery_min_v = excluded.battery_min_v, battery_max_v = excluded.battery_max_v, max_battery_power_kw = excluded.max_battery_power_kw, bms_family = excluded.bms_family, monitoring_support = excluded.monitoring_support;


-- Battery
INSERT INTO public.batteries (battery_id,name,nominal_capacity_kwh,nominal_voltage_v,min_operating_voltage_v,max_operating_voltage_v,max_charge_discharge_kw,max_parallel_units,bms_family) VALUES
('deye-rw-f10-2','Deye RW-F10.2',10.2,51.2,43.2,57.6,5.0,32,'Deye LV BMS')
ON CONFLICT (battery_id) DO UPDATE SET name = excluded.name, nominal_capacity_kwh = excluded.nominal_capacity_kwh, nominal_voltage_v = excluded.nominal_voltage_v, min_operating_voltage_v = excluded.min_operating_voltage_v, max_operating_voltage_v = excluded.max_operating_voltage_v, max_charge_discharge_kw = excluded.max_charge_discharge_kw, max_parallel_units = excluded.max_parallel_units, bms_family = excluded.bms_family;


-- suppliers and listings are left empty on purpose: we have no
-- Philippine quote yet, and a guessed price makes the budget check
-- lie. The app reports 'Needs changing' for Budget and Stock, which
-- is accurate. Add rows here when a real quote exists.
DELETE FROM public.listings;
DELETE FROM public.suppliers;

-- Presets. C2 is the build page's default.
INSERT INTO public.configurations (configuration_id,household_id,name,panel_id,panel_count,inverter_id,battery_id,battery_count,series_panels_per_string,parallel_strings_per_mppt,used_mppt_count,other_cost_allowance_php,status) VALUES
('C1','HH001','Budget','cec-ja-solar-jam72d30-550-mb',6,'deye-sun-3k-sg04lp1-eu','deye-rw-f10-2',1,6,1,1,25000,'demo_planning_only'),
('C2','HH001','Balanced','cec-ja-solar-jam72d30-550-mb',10,'deye-sun-5k-sg04lp1-eu','deye-rw-f10-2',1,10,1,1,25000,'demo_planning_only'),
('C3','HH001','Backup','cec-ja-solar-jam72d30-550-mb',14,'deye-sun-3-6k-sg04lp1-eu','deye-rw-f10-2',2,10,2,1,25000,'demo_planning_only')
ON CONFLICT (configuration_id) DO UPDATE SET household_id = excluded.household_id, name = excluded.name, panel_id = excluded.panel_id, panel_count = excluded.panel_count, inverter_id = excluded.inverter_id, battery_id = excluded.battery_id, battery_count = excluded.battery_count, series_panels_per_string = excluded.series_panels_per_string, parallel_strings_per_mppt = excluded.parallel_strings_per_mppt, used_mppt_count = excluded.used_mppt_count, other_cost_allowance_php = excluded.other_cost_allowance_php, status = excluded.status;


-- What the monitoring page simulates from.
INSERT INTO public.installed_systems (system_id,household_id,configuration_id,panel_capacity_kw,inverter_capacity_kw,battery_capacity_kwh,battery_min_soc_pct,battery_max_soc_pct,initial_soc_pct,solar_dc_to_bus_efficiency,battery_charge_efficiency,battery_discharge_efficiency,source) VALUES
('SYS001','HH001','C2',5.5,5.0,10.2,20.0,95.0,65.0,0.96,0.95,0.95,'synthetic_simulator')
ON CONFLICT (system_id) DO UPDATE SET household_id = excluded.household_id, configuration_id = excluded.configuration_id, panel_capacity_kw = excluded.panel_capacity_kw, inverter_capacity_kw = excluded.inverter_capacity_kw, battery_capacity_kwh = excluded.battery_capacity_kwh, battery_min_soc_pct = excluded.battery_min_soc_pct, battery_max_soc_pct = excluded.battery_max_soc_pct, initial_soc_pct = excluded.initial_soc_pct, solar_dc_to_bus_efficiency = excluded.solar_dc_to_bus_efficiency, battery_charge_efficiency = excluded.battery_charge_efficiency, battery_discharge_efficiency = excluded.battery_discharge_efficiency, source = excluded.source;


-- Now nothing refers to the fictional demo parts.
DELETE FROM public.panels WHERE panel_id IN ('P550','P450');
DELETE FROM public.inverters WHERE inverter_id IN ('I5000','I3000');
DELETE FROM public.batteries WHERE battery_id IN ('B512','BHV');
DELETE FROM public.suppliers WHERE supplier_id IN ('S1','S2');

COMMIT;

-- Check: SELECT count(*) FROM public.panels;
-- Expect 61.